### ISSUE TITLE
Failed to find element with selector: `table.Bs > tr`

### ISSUE THREAD

**Issue by kuhnster01** [InboxSDK/InboxSDK#1072]
Hi there, we are seeing this error in the console for users in Australia (but Gmail is potentially rolling this out further.  It may or may not be related to emails opening (as we have a separate issue) but we want to know if anyone else is seeing this InboxSDK specific
issue:

Sent by App: false 
Session Id: 1700115147601-0.4718526429030505 
Extension Id: chrome-extension://aohlfneeliakfcefeffppfplagbccbni/ 
InboxSDK Loader Version: 0.7.24-1484787998857-c248fbb55be579d3 
InboxSDK Implementation Version: 2.1.13-1699993741673-7af9b85c39a0158d
eval @ platform-implementation.js:23
Show 1 more frame
Show less
error-handler.js:192 2023-11-16T06:12:43.872Z: {"level":"error","message":"Logging chrome extension error to the server.","meta":{"message":"Logging chrome extension error to the server.","technical":"Failed to find element with selector: table.Bs > tr","originalError":{"message":"Failed to find element with selector: table.Bs > tr","stack":"Error: Failed to find element with selector: table.Bs > tr\n    at r (https://www.inboxsdk.com/build/platform-implementation.js:13:61559)\n    at He._startMonitoringPreviewPaneForThread (https://www.inboxsdk.com/build/platform-implementation.js:79:10452)\n    at He._setupContentAndSidebarView (https://www.inboxsdk.com/build/platform-implementation.js:79:10063)\n    at eval (https://www.inboxsdk.com/build/platform-implementation.js:79:9370)\n    at l.call (https://www.inboxsdk.com/build/platform-implementation.js:2:3304)\n    at MutationObserver.a (https://www.inboxsdk.com/build/platform-implementation.js:2:3550)\n    at v.invoke (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:6566)\n    at M.runGuarded (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:2085)\n    at MutationObserver.<anonymous> (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:1864)"},"logOnly":true,"time":"2023-11-16T06:12:43.872Z","ceVersion":"2.2.459.11749"},"name":"LogMessage"}
polyfills.js:1 Uncaught Error: Failed to find element with selector: table.Bs > tr
    at r (platform-implementation.js:13:61559)
    at He._startMonitoringPreviewPaneForThread (platform-implementation.js:79:10452)
    at He._setupContentAndSidebarView (platform-implementation.js:79:10063)
    at eval (platform-implementation.js:79:9370)
    at l.call (platform-implementation.js:2:3304)
    at MutationObserver.a (platform-implementation.js:2:3550)
    at v.invoke (polyfills.js:1:6566)
    at M.runGuarded (polyfills.js:1:2085)
    at MutationObserver.<anonymous> (polyfills.js:1:1864)
platform-implementation.js:23 Error logged: Error: Failed to find element with selector: table.Bs > tr
    at r (platform-implementation.js:13:61559)
    at He._startMonitoringPreviewPaneForThread (platform-implementation.js:79:10452)
    at He._setupContentAndSidebarView (platform-implementation.js:79:10063)
    at eval (platform-implementation.js:79:9370)
    at l.call (platform-implementation.js:2:3304)
    at MutationObserver.a (platform-implementation.js:2:3550)
    at v.invoke (polyfills.js:1:6566)
    at M.runGuarded (polyfills.js:1:2085)
    at MutationObserver.<anonymous> (polyfills.js:1:1864) 

Original error stack:
Error: Failed to find element with selector: table.Bs > tr
    at r (https://www.inboxsdk.com/build/platform-implementation.js:13:61559)
    at He._startMonitoringPreviewPaneForThread (https://www.inboxsdk.com/build/platform-implementation.js:79:10452)
    at He._setupContentAndSidebarView (https://www.inboxsdk.com/build/platform-implementation.js:79:10063)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:79:9370)
    at l.call (https://www.inboxsdk.com/build/platform-implementation.js:2:3304)
    at MutationObserver.a (https://www.inboxsdk.com/build/platform-implementation.js:2:3550)
    at v.invoke (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:6566)
    at M.runGuarded (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:2085)
    at MutationObserver.<anonymous> (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:1864) 

Error logged from:
    at L (https://www.inboxsdk.com/build/platform-implementation.js:23:9592)
    at D.error (https://www.inboxsdk.com/build/platform-implementation.js:23:6943)
    at D.run (https://www.inboxsdk.com/build/platform-implementation.js:23:6853)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:23:9843)
    at L.<computed> (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:28256)
    at v.invokeTask (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:7184)
    at M.runTask (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:2579)
    at invokeTask (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:8235)
    at invoke (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:8136)
    at m.args.<computed> (chrome-extension://aohlfneeliakfcefeffppfplagbccbni/components/polyfills.js:1:27968) 

[mail.google.com-1700115251843.log](https://github.com/InboxSDK/InboxSDK/files/13377904/mail.google.com-1700115251843.log)

**Comment by wegry** [comment]
Thanks for the report, we have a number of issues that might be related to this.

#1068 
#1070 
#1071

At Streak, we don't have access to an email account that can repro yet. @kuhnster01, do you? 

The failed selector is showing up in Sentry ([internal link](https://streak.sentry.io/issues/4546517967/?environment=production&project=4504322969763840&query=table.bS+%3E+tr&referrer=issue-stream&sort=user&statsPeriod=14d&stream_index=0))

**Comment by kuhnster01** [comment]
Hi Zach,

I have a user in Australia that is experiencing the issue, but I think he
has gone offline for the night.

If there is any thing you want me to ask him in particular, please let me
know.

I do have some elements that I copied from his DOM that may or may not be
useful.  If you want them, please send me your email address and I will
share them with you ***@***.***)

Thanks


Rodney Kuhn | Co-founder
083 456 7224 | www.sortd.com

**Comment by wegry** [comment]
@kuhnster01: About DOM snippets: We do have some telemetry around the DOM that was added here #1067.

Feel free to send over what you have though. You can reach me at `z ach [A T] streak.com` (without the space).

**Comment by wegry** [comment]
@kuhnster01 in the dom snippet you emailed over, I don't see the selector for preview panel. `div[role='main'] .aia`.

Based on the code [here](https://github.com/InboxSDK/InboxSDK/blob/8b8ba77af7e34ece908294217a4810724f6dbc89/src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts#L347) needs that Element present to get hit for the error above to be thrown. I wonder if Gmail has the element for a bit and then is removing it.

#1073 may help some folks. We'll keep monitoring on our side.

**Comment by wegry** [comment]
Fixed in #1086.
