### ISSUE TITLE
Bug: NavMenu.addNavItem() fails sometimes

### ISSUE THREAD

**Issue by Macil** [InboxSDK/InboxSDK#1156]
**Describe the bug**

While testing with the examples/custom-thread-list extension, sometimes on page load the extension throws an error and fails to add its navmenu buttons. I think the issue happens more often if I set Chrome's network tools to throttle the speed to "Slow 3g".

I think the issue happens because Gmail adds a certain nav container element to the page asynchronously, and the InboxSDK throws if that element isn't added to the page by the time NavMenu.addNavItem() is called. We probably need another waitFor somewhere.

```
Error logged: Error: should not happen
    at _createNavItemsHolder (add-nav-item.ts:128:41)
    at _getNavItemsHolder (add-nav-item.ts:115:12)
    at add-nav-item.ts:107:28
    at addNavItem (add-nav-item.ts:33:7) 

Original error stack:
Error: should not happen
    at _createNavItemsHolder (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:2864:41)
    at _getNavItemsHolder (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:2854:12)
    at chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:2847:84
    at addNavItem (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:2800:7) 

Error logged from:
    at logError (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:1143:82)
    at _logError (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:23364:64)
    at Logger.error (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:23144:5)
    at addNavItem (chrome-extension://mpcpiccfkhhjinilmfbmlblnhenbhdnf/inboxsdk.js:2803:59) 

Extension App Ids: [
  {
    "appId": "custom-thread-list"
  },
  {
    "appId": "custom-thread-list"
  },
  {
    "appId": "custom-thread-list"
  }
] 
Sent by App: false 
Session Id: 1712081555770-0.8773925159468541 
Extension Id: null 
InboxSDK Loader Version: 2.1.37-1711673787633-d66ff19bc410fcd4-MODIFIED-WATCH 
InboxSDK Implementation Version: 2.1.37-1711673787633-d66ff19bc410fcd4-MODIFIED-WATCH
```

**Version**

current git / npm build

**Comment by nik-lylo** [comment]
I have encountered the same problem. I have observed that this error occurs 90% of the time when **Gmail Chat** or **Google Meet** is enabled in the Gmail Settings. If either of them is enabled, the Google navigation panel will have a different view, which leads to the error.

**Comment by softlylove** [comment]
> I have encountered the same problem. I have observed that this error occurs 90% of the time when **Gmail Chat** or **Google Meet** is enabled in the Gmail Settings. If either of them is enabled, the Google navigation panel will have a different view, which leads to the error.
> 
> package version `2.1.64`

Cool!

1. After disabling both Meet and Chat, no errors occurred.

2. However, I noticed something strange: after disabling both, the newly added NavItem appears at the bottom of the left sidebar.

<img width="250" alt="image" src="https://github.com/user-attachments/assets/1a75c515-0820-4481-9171-fb843f3b1fd4">

**Comment by ViktorTassen** [comment]
I confirm same issue - after disabling apps (Chat and Meet), the newly added NavItem appears at the bottom of the left sidebar. How to fix?
