### ISSUE TITLE
Bug: Missing _attachmentCardImplementation._element properties of the callback handler registerFileAttachmentCardViewHandler

### ISSUE THREAD

**Issue by shashikiran-im** [InboxSDK/InboxSDK#1162]
Hi InboxSDK team,
				
**Issue:**
From few of days back the inboxSDK API method registerFileAttachmentCardViewHandler() is not returning the property "attachmentCardImplementation._element" in the callback parameter (card) in Chrome extension Manifest V2 as shown below.
(NOTE: It was working until mid of Mar-2024)
				
**Sample code:**
InboxSDK.load(1, 'YOUR_APP_ID_HERE').then(function(sdk) {
  sdk.Conversations.registerFileAttachmentCardViewHandler(card => {
console.log("Attachment card element: ", card._attachmentCardImplementation._element);     //Error: Cannot read properties of undefined (reading '_element')
});
});

**Below is the error in console:**
Error logged: TypeError: Cannot read properties of undefined (reading '_element')
				    at addButtonToGmailAttachments.js:20:85
				    at u (platform-implementation.js:13:66625)
				    at l._informHandlersOfTarget (platform-implementation.js:13:66594)
				    at l.addTarget (platform-implementation.js:13:66284)
				    at eval (platform-implementation.js:57:3497)
				    at _ (platform-implementation.js:114:382140)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at b._emitValue (platform-implementation.js:114:383880)
				    at b._handleValue (platform-implementation.js:114:397807)
				    at b._handleAny (platform-implementation.js:114:391550)
				    at _$handleAny (platform-implementation.js:114:391289)
				    at _ (platform-implementation.js:114:382109)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at b._emitValue (platform-implementation.js:114:383880)
				    at b._handleValue (platform-implementation.js:114:400397)
				    at b._handleAny (platform-implementation.js:114:391550)
				    at _$handleAny (platform-implementation.js:114:391289)
				    at _ (platform-implementation.js:114:382109)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at b._emitValue (platform-implementation.js:114:383880)
				    at b._handleValue (platform-implementation.js:114:397483)
				    at b._handleAny (platform-implementation.js:114:391550)
				    at _$handleAny (platform-implementation.js:114:391289)
				    at _ (platform-implementation.js:114:382109)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at sn._emitValue (platform-implementation.js:114:383880)
				    at sn._emit (platform-implementation.js:114:383748)
				    at sn._addToCur (platform-implementation.js:114:409684)
				    at sn._add (platform-implementation.js:114:409217)
				    at sn._handleMain (platform-implementation.js:114:415027)
				    at _$handleMain (platform-implementation.js:114:412672)
				    at _ (platform-implementation.js:114:382109)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at b._emitValue (platform-implementation.js:114:383880)
				    at b._handlePrimaryValue (platform-implementation.js:114:413118)
				    at b._handlePrimaryAny (platform-implementation.js:114:413439)
				    at _$handlePrimaryAny (platform-implementation.js:114:412984)
				    at _ (platform-implementation.js:114:382109)
				    at g.dispatch (platform-implementation.js:114:383212)
				    at sn._emitValue (platform-implementation.js:114:383880) 
				
Please let me know if anybody facing similar issue.
I kindly request you to let me know is there is any fix available for the same as this feature is broken in my extension for end users.

Thanks in advance,
Shashikiran

**Comment by wegry** [comment]
Neither of the fields above on card are publicly documented as part of our API. `_` prefixed fields, by convention, are "non-public" and subject to change without notice.

PRs welcome to make these fields exposed publicly.

**Comment by Macil** [comment]
In general we can't guarantee flawless support for applications using the remote-loaded MV2 InboxSDK in unintended ways, but for this case we've pushed out a workaround now that makes the `AttachmentCardView._attachmentCardImplementation._element` property work again, with a warning that suggests using the new `AttachmentCardView.getElement()` method instead.
