### ISSUE TITLE
getDownloadUrl() is failing with "returned unexpected url https://mail.google.com/mail/u/0/"

### ISSUE THREAD

**Issue by albaraks** [InboxSDK/InboxSDK#1204]
**Describe the bug**

The API event.getDownloadURL() is failing with the latest update of Chrome browser Version 126.0.6478.57 (Official Build) (64-bit)

The attachment is .html file type, if we try with a different file type then the API works as expected. 

m=b:962 Error logged: 
Error: getDownloadURL returned unexpected url
    at GmailAttachmentCardView.getDownloadURL (inboxsdk.js:11707:23)
 

Original error stack:
Error: getDownloadURL returned unexpected url
    at GmailAttachmentCardView.getDownloadURL (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11707:23) 

Error logged from:
    at logError (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:10464:22)
    at _logError (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11011:3)
    at Logger.error (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:10794:5)
    at GmailAttachmentCardView.getDownloadURL (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11708:36) 

Error details: 
{finalUrlCensored: 'https://mail.google.com/mail/u/0/'}
finalUrlCensored
: 
"https://mail.google.com/mail/u/0/"
[[Prototype]]
: 
Object
 

**Reproduction steps**

1. Add a button to the attachment card
2. Register event on new added button
3.Call getDownloadUrl() API
4.

**Expected behavior**

Should return short-lived url to download email attachment

**Screenshots**

m=b:962 Error logged: 
Error: getDownloadURL returned unexpected url
    at GmailAttachmentCardView.getDownloadURL (inboxsdk.js:11707:23)
 

Original error stack:
Error: getDownloadURL returned unexpected url
    at GmailAttachmentCardView.getDownloadURL (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11707:23) 

Error logged from:
    at logError (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:10464:22)
    at _logError (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11011:3)
    at Logger.error (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:10794:5)
    at GmailAttachmentCardView.getDownloadURL (chrome-extension://niheegnkfppndpacpkkaogafhloimapd/inboxsdk.js:11708:36) 

Error details: 
{finalUrlCensored: 'https://mail.google.com/mail/u/0/'}
finalUrlCensored
: 
"https://mail.google.com/mail/u/0/"
[[Prototype]]
: 
Object
 

**Version**

Are you using the remote loaded SDK or bundled from NPM? if NPM, which version?

all versions

**Add any other context about the problem here if anything**

This was working for years and just after updating the chrome browser, we  are observing this failure.

**Comment by albaraks** [comment]
Additional testing revealed this is broken for .html attachments. If we try with other file type then the api works as expected.

**Comment by Macil** [comment]
Thanks for the report! This has been fixed in the latest version.
