### ISSUE TITLE
15 seconds timeout while loading

### ISSUE THREAD

**Issue by briziodane** [InboxSDK/InboxSDK#781]
How can I fix ths Error while I use a delegate account
 15 second timeout while waiting for sidebar fired

 at eval (platform-implementation.js:35:12535)
    at Ue._add (platform-implementation.js:8:23816)
    at Ue._handleMain (platform-implementation.js:8:27446)
    at Ue._$handleMain (platform-implementation.js:8:1523)
    at b (platform-implementation.js:7:22828)
    at _.dispatch (platform-implementation.js:8:5159)
    at t._emitValue (platform-implementation.js:8:5817)
    at t._onTick (platform-implementation.js:8:9196)
    at _$onTick (platform-implementation.js:7:23314)
    at eval (platform-implementation.js:51:9565)
    at Function.value (platform-implementation.js:51:15238)
    at eval (platform-implementation.js:51:9541) 

Original error stack:
Error: 15 second timeout while waiting for sidebar fired
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:35:12535)
    at Ue._add (https://www.inboxsdk.com/build/platform-implementation.js:8:23816)
    at Ue._handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:27446)
    at Ue._$handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:1523)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at t._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at t._onTick (https://www.inboxsdk.com/build/platform-implementation.js:8:9196)
    at _$onTick (https://www.inboxsdk.com/build/platform-implementation.js:7:23314)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9565)
    at Function.value (https://www.inboxsdk.com/build/platform-implementation.js:51:15238)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9541) 

Error logged from:
    at n (https://www.inboxsdk.com/build/platform-implementation.js:20:22045)
    at l (https://www.inboxsdk.com/build/platform-implementation.js:51:9267)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:51:14050)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:35:12679)
    at Fe._add (https://www.inboxsdk.com/build/platform-implementation.js:8:23816)
    at Fe._handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:27923)
    at Ue._$handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:1523)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at y._emitError (https://www.inboxsdk.com/build/platform-implementation.js:8:5899)
    at y._handleError (https://www.inboxsdk.com/build/platform-implementation.js:8:14339)
    at y._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:7:26333)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:7:26029)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at y._emitError (https://www.inboxsdk.com/build/platform-implementation.js:8:5899)
    at y._handleError (https://www.inboxsdk.com/build/platform-implementation.js:7:26179)
    at y._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:7:26333)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:7:26029)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at Pe._emitError (https://www.inboxsdk.com/build/platform-implementation.js:8:5899)
    at Pe._handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:8:25171)
    at Le._$handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:8:880)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at Ue._emitError (https://www.inboxsdk.com/build/platform-implementation.js:8:5899)
    at Ue._emit (https://www.inboxsdk.com/build/platform-implementation.js:8:5717)
    at Ue._addToCur (https://www.inboxsdk.com/build/platform-implementation.js:8:24230)
    at Ue._add (https://www.inboxsdk.com/build/platform-implementation.js:8:23806)
    at Ue._handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:27446)
    at Ue._$handleMain (https://www.inboxsdk.com/build/platform-implementation.js:8:1523)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at t._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at t._onTick (https://www.inboxsdk.com/build/platform-implementation.js:8:9196)
    at _$onTick (https://www.inboxsdk.com/build/platform-implementation.js:7:23314)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9565)
    at Function.value (https://www.inboxsdk.com/build/platform-implementation.js:51:15238)

**Comment by wegry** [comment]
@briziodane is this issue still affecting you?

**Comment by wegry** [comment]
If you're still seeing this issue, feel free to reopen.
