### ISSUE TITLE
"Failed to find gmail supportMenu" logged to console

### ISSUE THREAD

**Issue by amiram** [InboxSDK/InboxSDK#795]
**Describe the bug**
When loading Gmail, inboxsdk handlers are not working. After 10 seconds I see this error in the console

```
Error logged: Error: Failed to find gmail supportMenu
    at eval (platform-implementation.js:22:13293)
    at b (platform-implementation.js:7:22861)
    at v.dispatch (platform-implementation.js:8:5159)
    at y._emitValue (platform-implementation.js:8:5817)
    at y._handlePrimaryValue (platform-implementation.js:8:1970)
    at y._handlePrimaryAny (platform-implementation.js:8:2292)
    at _$handlePrimaryAny (platform-implementation.js:8:1836)
    at b (platform-implementation.js:7:22828)
    at v.dispatch (platform-implementation.js:8:5159)
    at t._emitValue (platform-implementation.js:8:5817)
    at t._onTick (platform-implementation.js:8:9196)
    at _$onTick (platform-implementation.js:7:23314)
    at eval (platform-implementation.js:51:9341)
    at Function.value (platform-implementation.js:51:15095)
    at eval (platform-implementation.js:51:9317) 

Original error stack:
Error: Failed to find gmail supportMenu
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:22:13293)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22861)
    at v.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at y._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at y._handlePrimaryValue (https://www.inboxsdk.com/build/platform-implementation.js:8:1970)
    at y._handlePrimaryAny (https://www.inboxsdk.com/build/platform-implementation.js:8:2292)
    at _$handlePrimaryAny (https://www.inboxsdk.com/build/platform-implementation.js:8:1836)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at v.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at t._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at t._onTick (https://www.inboxsdk.com/build/platform-implementation.js:8:9196)
    at _$onTick (https://www.inboxsdk.com/build/platform-implementation.js:7:23314)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9341)
    at Function.value (https://www.inboxsdk.com/build/platform-implementation.js:51:15095)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9317) 

Error logged from:
    at n (https://www.inboxsdk.com/build/platform-implementation.js:20:22045)
    at l (https://www.inboxsdk.com/build/platform-implementation.js:51:9043)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:51:13866)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:51:14008)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:22:13283)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22861)
    at v.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at y._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at y._handlePrimaryValue (https://www.inboxsdk.com/build/platform-implementation.js:8:1970)
    at y._handlePrimaryAny (https://www.inboxsdk.com/build/platform-implementation.js:8:2292)
    at _$handlePrimaryAny (https://www.inboxsdk.com/build/platform-implementation.js:8:1836)
    at b (https://www.inboxsdk.com/build/platform-implementation.js:7:22828)
    at v.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:8:5159)
    at t._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:8:5817)
    at t._onTick (https://www.inboxsdk.com/build/platform-implementation.js:8:9196)
    at _$onTick (https://www.inboxsdk.com/build/platform-implementation.js:7:23314)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9341)
    at Function.value (https://www.inboxsdk.com/build/platform-implementation.js:51:15095)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:51:9317) 
```5y6tu4
**To Reproduce**
Steps to reproduce the behavior:
 
1. Just use inboxsdk

**Add any other context about the problem here if anything**
This error was around few weeks ago but got fixed. Now I see it again.

**Comment by amiram** [comment]
I see in the code that the selector for the support menu is `header[role=banner] div:not([aria-label]):not([data-ogsr-up]) > div:not(.inboxsdk__appButton) > div[data-tooltip] + div[role=menu]`. When I use the selector in the console I get the correct node, but only few seconds after the page loads.
The node html is:
```
<div id="M842Cd" class="t9" role="menu" tabindex="0" aria-hidden="true" style="display: none;">
   <div class="ua" aria-label="Help" tabindex="-1" role="menuitem" jsname="j7LFlb">Help</div>
   <div class="ua" aria-label="Training" tabindex="-1" role="menuitem" jsname="j7LFlb">Training</div>
   <div class="ua" aria-label="Updates" tabindex="-1" role="menuitem" jsname="j7LFlb">Updates</div>
   <div class="ub" role="separator" aria-hidden="true"></div>
   <div class="ua" aria-label="Send feedback to Google" tabindex="-1" role="menuitem" jsname="j7LFlb">Send feedback to Google</div>
</div>
```

**Comment by aleemstreak** [comment]
Can you help us reproduce this? It seems to be only happening on a very
small number of accounts according to the telemetry. Is there something
special about the account its happening on?
ᐧ

**Comment by amiram** [comment]
There is nothing special in this account. It's a Google Workspace account. In the quick settings I see this `You're using the new Gmail view`. In admin console we use the rapid release for new features. It is still happening and we can debug it together.

**Comment by aleemstreak** [comment]
Yeah would love if you can track down where the current code is failing. We enabled sourcemaps recently so you should be able to step through it

**Comment by amiram** [comment]
I'm not using the npm package. It fails here:
```
Kefir.later(45 * 1000)
      .takeUntilBy(
        toItemWithLifetimeStream(this._page.tree.getAllByTag('supportMenu'))
      )
      .onValue(() => {
        this._logger.errorSite(new Error('Failed to find gmail supportMenu'));
      });
```
Why do you throw this error when you get the value of the support menu?

**Comment by amiram** [comment]
I had this issue for a couple of days now. Today it disappeared and then came back. I had to kill the tab process for some reason and right after that the issue was gone.

**Comment by wegry** [comment]
@amiram source maps should be available even for the remote loaded version of the SDK as of 2022-10-14, give or take a few days.

> I had this issue for a couple of days now. Today it disappeared and then came back.

I've experienced this issue as well (mostly during development), but haven't ever been able to track down the root cause.

**Comment by amiram** [comment]
@wegry I'm not 100% sure but I saw this happening after using the debugger in devtools and refreshing the page when a breakpoint hits. Killing the tab solved it.

**Comment by blackwolf3342** [comment]
> @wegry I'm not 100% sure but I saw this happening after using the debugger in devtools and refreshing the page when a breakpoint hits. Killing the tab solved it.

I can confirm that I've just gotten this error and solving was killing the tab.
