### ISSUE TITLE
Error: Failed to find nav item

### ISSUE THREAD

**Issue by F-y-o-d-o-r** [InboxSDK/InboxSDK#884]
v1.0.4 - after the extension install or sometimes after reload of the page
Error logged: Error: Failed to find nav item
    at c (inboxsdk.js:143:198625)
    at n.default (inboxsdk.js:143:160009) 
Original error stack:
Error: Failed to find nav item
    at c (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:143:198625)
    at n.default (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:143:160009) 
Error logged from:
    at n.default (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:143:56113)
    at I (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:252:7021)
    at S.error (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:252:5826)
    at c (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:143:198619)
    at n.default (chrome-extension://kibfopgnjcjgblnojndmnjcdnmaghedd/js/utils/inboxsdk.js:143:160009) 

![image](https://user-images.githubusercontent.com/25505945/228599356-0e368a3e-7dc6-4dd6-9972-a4eb09cb1140.png)

**Comment by 1TheMuffinMan** [comment]
Having the same issue

**Comment by wegry** [comment]
I managed to trigger this error with [an example extension](https://github.com/InboxSDK/InboxSDK/blob/64bff328fecb9d5854677c89fa6c33fc1c38c6ae/examples/compose-tooltip-button/content.js#L4)

Stack trace with source maps

```
inboxsdk.js:1735 Error logged: Error: Failed to find nav item
    at isDarkTheme (inboxsdk.js:5622:63)
    at gmailLoadEvent (inboxsdk.js:3833:82) 

Original error stack:
Error: Failed to find nav item
    at isDarkTheme (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:5622:63)
    at gmailLoadEvent (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:3833:82) 

Error logged from:
    at logError (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:1719:82)
    at _logError (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:23605:64)
    at Logger.error (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:23388:5)
    at isDarkTheme (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:5622:57)
    at gmailLoadEvent (chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/inboxsdk.js:3833:82) 

Extension App Ids: [
  {
    "appId": "simple-example"
  }
] 
Sent by App: false 
Session Id: 1691000019023-0.40742939578700454 
Extension Id: chrome-extension://cdocalkpnnafjienffbkmlgfdokghmpe/ 
InboxSDK Loader Version: 0.7.25-1690914166116-1ccd156ad64a143a-MODIFIED-WATCH 
InboxSDK Implementation Version: 0.7.25-1690914166116-1ccd156ad64a143a-MODIFIED-WATCH 
Is Using Sync API: true
```

I think the fix might just involve waiting for nav menu item selectors to come up like we do in [here](https://github.com/InboxSDK/InboxSDK/blob/64bff328fecb9d5854677c89fa6c33fc1c38c6ae/src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-nav-item.ts#L45) for other parts of the `gmailLoadEvent`.
