### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by pbosakov** [InboxSDK/InboxSDK#943]
**Describe the bug**
When switching to a different category tab in Gmail, errors are reported in the console:
```
pageWorld.js:2 Error in injected script Error: Errors in thread row parsing
    at P (pageWorld.js:2:1)
    at pageWorld.js:2:1
    at HTMLDocument.<anonymous> (pageWorld.js:2:1) {errors: [
        "failed to find timeSpan",
        "failed to find peopleDiv"
    ]}
```

**To Reproduce**

1. [Enable category tabs](https://support.google.com/mail/answer/3094499) in Gmail
2. Open the developer console
3. Open inbox and click to a different tab (e.g. _Promotions_)

**Screenshots**
![inboxsdk-screenshot](https://github.com/InboxSDK/InboxSDK/assets/1148312/1583be78-288f-4d41-94b6-011fa5918137)
![inboxsdk-console](https://github.com/InboxSDK/InboxSDK/assets/1148312/5afb4e6a-3be3-4f36-85ff-487e098b180d)

**Comment by wegry** [comment]
Notably, it seems I can repro this issue on a Gmail account but not on a Google Workspace account.

**Comment by wegry** [comment]
Digging a bit more: unfortunately, there is no `timeSpan` equivalent in the _Promotions_ or _Social _ tabs.

See https://github.com/InboxSDK/InboxSDK/blob/2dadf97d932691251f5dc508213819a95cc2358e/src/injected-js/gmail/thread-identifier/thread-row-parser.ts#L36 for the `timeSpan` element selector that works in the Primary tab.

`peopleDiv` _could_ be potentially be remapped to the left most column name. In the [example above](https://user-images.githubusercontent.com/1148312/252630560-1583be78-288f-4d41-94b6-011fa5918137.png) that'd be `Tripadvisor`.

Whether or not we could look up non Primary tab thread information based on the equivalent (or lack of one) is an open question.

**Comment by wegry** [comment]
With respect to

> Whether or not we could look up non Primary tab thread information based on the equivalent (or lack of one) is an open question.

It appears that even with this [example extension](https://github.com/InboxSDK/InboxSDK/blob/main/examples/thread-rows/content.js) and this diff: 

```
diff --git a/src/injected-js/gmail/thread-identifier/thread-row-parser.ts b/src/injected-js/gmail/thread-identifier/thread-row-parser.ts
index 420be1f4..d7814feb 100644
--- a/src/injected-js/gmail/thread-identifier/thread-row-parser.ts
+++ b/src/injected-js/gmail/thread-identifier/thread-row-parser.ts
@@ -10,7 +10,7 @@ export type ThreadRowMetadata = {
 export function extractMetadataFromThreadRow(
   threadRow: HTMLElement
 ): ThreadRowMetadata {
-  var timeSpan, subjectSpan, peopleDiv;
+  let timeSpan, subjectSpan, peopleDiv;
   assert(threadRow.hasAttribute('id'), 'check element is main thread row');
   var errors = [];
   var threadRowIsVertical =
@@ -46,17 +46,17 @@ export function extractMetadataFromThreadRow(
     peopleDiv = threadRow.querySelector('td.yX > div.yW');
   }
 
-  if (!timeSpan) {
-    errors.push('failed to find timeSpan');
-  }
+  // if (!timeSpan) {
+  //   errors.push('failed to find timeSpan');
+  // }
 
   if (!subjectSpan) {
     errors.push('failed to find subjectSpan');
   }
 
-  if (!peopleDiv) {
-    errors.push('failed to find peopleDiv');
-  }
+  // if (!peopleDiv) {
+  //   errors.push('failed to find peopleDiv');
+  // }
 
   if (errors.length) {
     logger.error(new Error('Errors in thread row parsing'), {
diff --git a/src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts b/src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
index 5f7d868f..b585628e 100644
--- a/src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
+++ b/src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
@@ -278,15 +278,18 @@ class GmailThreadRowView {
     return this._alreadyHadModifications;
   }
 
-  // Returns a Kefir stream that emits this object once this object is ready for the
-  // user. It should almost always synchronously ready immediately, but there's
-  // a few cases such as with multiple inbox or the drafts page that it needs a moment.
-  // make sure you take until by on the gmailThreadRowView.getStopper() because waitForReady
-  // must not be called after the gmailThreadRowView is destroyed
+  /**
+   * @returns a Kefir stream that emits this object once this object is ready for the user.
+   *
+   * It should almost always synchronously ready immediately, but there's
+   * a few cases such as with multiple inbox or the drafts page that it needs a moment.
+   * make sure you take until by on the @see GmailThreadRowView#getStopper because waitForReady
+   * must not be called after the GmailThreadRowView is destroyed
+   */
   waitForReady(): Kefir.Observable<GmailThreadRowView, unknown> {
     const time = [0, 10, 100, 1000, 15000];
 
-    const step: any = () => {
+    const step = (): Kefir.Observable<GmailThreadRowView | never, unknown> => {
       if (this._threadIdReady()) {
         asap(() => {
           if (this._elements.length) this._removeUnclaimedModifications();
```

That we end up with a `Should not happen: ThreadRowViewDriver never became ready` being logged when navigating to the Promotions tab.

**Comment by wegry** [comment]
> there is no timeSpan equivalent in the Promotions or _Social _ tabs.

To qualify this a bit, there is no SDK equivalent `timeSpan` or `peopleDiv` equivalent for ads. Specifically thread data coming from requests that look vaguely like https://mail-ads.google.com/mail/u/0/ads/main_jspb?rt=r&client=25&pt=ji. Gmail's docs go into the annotation process here https://developers.google.com/gmail/promotab/overview.

Here's an example image of a _Promotions_ tab thread row the SDK parses without complaint:

<img width="1441" alt="Screenshot 2023-08-03 at 14 34 05" src="https://github.com/InboxSDK/InboxSDK/assets/5156873/4016a15b-f047-41ee-ad40-4a7e0bab6bbd">

> it seems I can repro this issue on a Gmail account but not on a Google Workspace account.

I believe the Gmail/Google Workspace account distinction was a red herring. My Google Workspace account didn't have any _Promotions_ tab ads was all.
